### ISSUE TITLE
minhash class __init__ function

### ISSUE THREAD

**Issue by SofiaArancibia** [ekzhu/datasketch#101]
Hi!
I was trying to test different permutation numbers and got the error:
"`ValueError: Expecting minhash with length 129, got 128`" and after checking the __init__ method found that there's a default value that is never updated with the parameter value:

def __init__(self, **num_perm=128**, seed=1,
            hashfunc=sha1_hash32,
            hashobj=None, # Deprecated.
            hashvalues=None, permutations=None):
        **if hashvalues is not None:
            num_perm = len(hashvalues)
        if num_perm > _hash_range:**

Can you check, please?

**Comment by ekzhu** [comment]
The default value should be updated if you set `num_perm=256`, for example. Right? It would be more helpful if you can copy the code that calls the constructor.

**Comment by SofiaArancibia** [comment]
@ekzhu exactly!
Here's an example:

```
minhash_objects = []
threshold = 0.5
num_perm = 128
tag = 0

for idx, row in my_df.iterrows():
    m = MinHash(num_perm=num_perm)   # here, if I change num_perm, the default value should be updated
    for elem in row:
        m.update(elem.encode("utf-8"))
    ....
```

**Comment by ekzhu** [comment]
The error message "Expecting minhash with length..." is part of the LSH algorithm. Not in MinHash. I was confused because the example you provided doesn't show that you are using LSH.

`MinHashLSH` requires all MinHash to have the same `num_perm`. So you can't insert a MinHash with a different `num_perm` into an existing `MinHashLSH`.

You can initialize `MinHashLSH` with your own `num_perm` setting if that's what you want.

**Comment by ekzhu** [comment]
Can we close this?
