### ISSUE TITLE
Store MinhashLSH results for millions of records

### ISSUE THREAD

**Issue by dan9401** [ekzhu/datasketch#125]
Thanks for the library!

I'm developing an web application for fast search of similar records in a table that has more than 200 million records. So I want to build a lsh object and store it, and use it for fast lookup for user.

What I'm thinking is creating a table (in a database) where each column stores hash values for 1 band, and for the use the same lsh object for the query (I assume the lsh object can do that as long as the same permutations are used), and lookup the same hash values in the table. I assume this is a reasonable scheme?

I tried to pickle a lsh object with 1 million records, and it was around 200MB, so likely it's not optimal to store all the information for 2 billion locally at once. I'm wondering is there a way for me to **delete the inserted keys** in the lsh object?

Thanks! I've read #19 , #96 and #121 , but I'm still wondering is my idea legitimate. And if so, how should I do that?

**Comment by ekzhu** [comment]
Hi! I made [this repo](https://github.com/ekzhu/go-sql-lsh) to implement LSH in Postgres and SQLite.

From my experience, this scheme may work well for maybe a few millions, but I am not sure about 200 millions. The index lookup for every band can be quite expensive: if you hit a large hash bucket then the cost would be O(n) the number keys in that bucket, and this is much more likely when you have 200 millions records. Then, the subsequent `select distinct` operation to combine results from different band will stall -- maybe even exceed memory buffer if unlucky.

Because you are now dealing with so many records maybe the key is to limit your result size. So a threshold-based query algorithm (as in `MinHashLSH`) may not be as good as top-k algorithm with very high selectivity (see `MinHashLSHForest`). Unfortunately `MinHashLSHForest` is implemented in pure Python, it is far away from being memory-efficient.

That being said, I think there is a opportunity for a database-backed implementation of `MinHashLSHForest` that can scale. 

For deletion: http://ekzhu.com/datasketch/documentation.html#datasketch.MinHashLSH.remove
