### ISSUE TITLE
NameError: name 'RedisSetStorage' is not defined

### ISSUE THREAD

**Issue by JadeXIN** [ekzhu/datasketch#166]
when i run this code:
 lsh = MinHashLSH(threshold=threshold, num_perm=num_perm, storage_config=storage_config)

i got this error:
NameError: name 'RedisSetStorage' is not defined

what's the reason of this error.

**Comment by Zoufuheng** [comment]
请问这个问题是怎么解决的？我也遇到了一样的问题

**Comment by ekzhu** [comment]
Can you provide the complete code?

**Comment by Zoufuheng** [comment]
Hello, the problem has been resolved because there are no dependencies associated with installation







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ekzhu/datasketch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月23日(星期天) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ekzhu/datasketch] NameError: name 'RedisSetStorage' is not defined (#166)





 
Can you provide the complete code?
