### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by gosom** [ekzhu/datasketch#28]
Thanks for the well written library.

The library is using too much memory (>1GB) for around 300.000 LeanMinHashes.

a. You use maxhash of 32 bits but your np arrays are using dtype=uint64.
   I do not know how numpy memory allocation works but I think it maybe allocates double the needed size.
b. You have an implementation of bMinHash. Does it work? If yes can you give me an example?

**Comment by ekzhu** [comment]
a. Thanks for pointing it out. The reason 64 bit is used is because during the calculation of hash values, using 32-bit integers may cause overflow. Could you suggest a better way to handle this?
b. It works. But I no longer maintain it, as it offers no actual memory efficiency for it uses np.int to store each hash value.
