### ISSUE TITLE
crash when run with python to C size mismatch

### ISSUE THREAD

**Issue by sagi-schein** [ekzhu/datasketch#4]
when running the example code in the site I get the following error :
OverflowError Python int too large for C long
the environment is 
windows 7 64 bit, Python 3.5.1  |Anaconda 4.0.0
library version 0.2.3

**Comment by jcardonnet** [comment]
Seems to be a Windows-specific issue regarding numpy. I made a pull request to fix the issue but requires numpy >= 1.11.0

**Comment by sagi-schein** [comment]
BTW - when I change line 51 to dtype=np.int64 the crash moves to the call to randint() in line 60

**Comment by jcardonnet** [comment]
Make sure you also add dtype=np.int64 on lines 60 and 61:

**Comment by ekzhu** [comment]
@sagi-schein Thanks for the spotting! The bug is Windows specific because on Windows the default int (C long) is 32-bit. It is 64-bit on UNIX, and I don't have Windows. So I have never spotted it before.

Because the constant `_max_hash` requires at least 32-bit, but the [initialization of the `hashvalues`](https://github.com/ekzhu/datasketch/blob/master/datasketch/minhash.py#L51) uses `np.int`, which has 31 value bits (1 for sign). So changing that to `np.int64` or `np.uint64` is a good idea.

The constant `_mersenne_prime` uses more than 32 bits so the default int overflowed (on Windows).

@jcardonnet thanks for the pull request. I made some comments. Perhaps you can help me make a few more changes?

**Comment by sagi-schein** [comment]
thanks.

**Comment by ekzhu** [comment]
I submitted a patch, it should work on windows now.
