### ISSUE TITLE
Easy computation of all duplicates?

### ISSUE THREAD

**Issue by fjsj** [ekzhu/datasketch#76]
Thanks for this library!

One question: Is there an easy way to get all pairs from a LSH?
In other words, instead of a query for a single minhash, I need all pairs of records inside a same bucket.

I tried to dive into the code, but I didn't understand very well how hashranges/hashtables work.
What I need is similar to `candidate_duplicates` of this other implementation: https://mattilyra.github.io/2017/05/23/document-deduplication-with-lsh.html

**Comment by aastafiev** [comment]
Hello,

You can code the same function as proposed in the article. MinHash and MinHashLSH interfaces are enough to do this.


---------------------
Sincerely yours,
Aleksey Astafiev

**Comment by ekzhu** [comment]
In MinHashLSH, if you are using the default storage config option(i.e., dict), the `hashtables` would be just a `list` of a subclass of `collection.defaultdict` types. So for each hash table, you could just iterate over the keys and get the bucket as a `list`, and for each list, you can generate all pairs for that bucket. If you do this for all hash tables, and deduplicate the results, you can get all pairs produced by the MinHashLSH.

**Comment by fjsj** [comment]
Thanks @ekzhu and @aastafiev , that explanation makes things clearer. Closing the issue.

**Comment by tsela** [comment]
Sorry for hijacking this already closed thread, but I need some additional advice on this topic.

I've used the method described above with great success, helping me deduplicate a dataset of about 14000 documents, removing 4000 relatively quickly and without having to throw enormous amounts of memory and CPU at it.

However, I am concerned with the Jaccard similarity measure's (and thus `MinHashLSH`'s) issue with sets of widely varying sizes, and I've wanted to try out the same thing (computation of all (near) duplicates in my dataset) using Containment instead (my documents have a wide range of sizes so I'm concerned I'm missing duplicates if using a plain `MinHashLSH`). I guess that means I need to use `MinHashLSHEnsemble` instead of `MinHashLSH`, since that is the LSH for Containment search. The problem is that after that, I have no idea how to get all (near) duplicate pairs from the resulting LSH. Can anyone provide me with some guidance on this? Is there a way to generate all the duplicate pairs with `MinHashLSHEnsemble` in a similar way to the method described above for `MinHashLSH`?

Thanks in advance for your help.

**Comment by ekzhu** [comment]
MinHashLSHEnsemble doesn't give you of all pairs the same way I mentioned earlier in this thread. You just have to build a complete index of all documents, and then query the index with every document `Q` to find other documents `X` that contains `Q`.

I am curious. If you are looking for near-duplicates, then Jaccard should be the right measure. What is your definition of duplicates?

**Comment by tsela** [comment]
OK, that makes sense. At least I only have to do a single pass to get all the duplicates.

My definition of duplicates is probably close to yours, but I have to handle wildly varying document sizes, and I have cases of one document mostly contained in another, much larger document, that are not adequately handled by Jaccard (I consider those near duplicates too and want to remove the smaller document when that happens). That's why I want to try and see whether Containment is giving me better results.

**Comment by ekzhu** [comment]
Cool! Thanks for the info.

**Comment by sameertikoo** [comment]
@ekzhu 
Sorry for piling on but I really didnt know where else to get the best information about this.

So I have a list of 150,000 + IT incident short description's and I want to get all the similar incidents in a cluster/group/bucket however as per my understanding for each 150,000+ keys we have a a hash/list of the similar incidents(as line numbers) .
Now,  my final goal is that I just want the bucket of similar incidents and those incidents should not be present in another bucket.(This is where I am struggling to understand how to get all the unique lists with the incident/line_number occurring only once in all the hastables)

For example considering a set of 5 incident summaries represented with their similarity.

{
1: 1,3,4
2: 2
3: 1,3,5
4:1,3,4
5: 1,3,5
}

What should be the best approach to tackle this ?

**Comment by ekzhu** [comment]
My understanding is that now you have pairs of incidents that are similar. Based on your example, the pairs are: `(1, 3), (1, 4), (3, 5), (4, 3), (5, 1)`, removing the duplicate pairs and self pairs. So if you think of every pair as an edge and each incident as a node, what you are looking for is a "clique" -- in graph term this means a group of nodes that are connected to each other, but not other node. Maybe you can look for graph algorithms that find cliques?

**Comment by fjsj** [comment]
@sameertikoo that's called the transitivity problem on Record Linkage. [Check those slides, page 32](https://www2.cs.duke.edu/courses/spring17/compsci590.1/lectures/14-er-intro.pdf). Quick solution is to make the pairs a graph and compute the connected components. Use [networkx](https://networkx.github.io/) for that (or [networkit](https://networkit.github.io/) if your graph has millions of edges). For an introduction on Record Linkage and the Transitivity problem, [I have a talk on deduplication with Python](https://youtu.be/4O87RdBgRJ4).

**Comment by ekzhu** [comment]
@sameertikoo the expert has spoken

**Comment by sameertikoo** [comment]
@ekzhu @fjsj Damn why didn't i get a notification on GitHub about your comments 😷.
Just saw this now and will try this asap.

**Comment by sameertikoo** [comment]
Perhaps this is what was meant.
So first I have to get the pairs. Currently I have the minhash dictionary with the line number as key and all the similar lines.
And the result should be something like we have in the screenshot.


![image](https://user-images.githubusercontent.com/15632991/69369976-075e5480-0cc3-11ea-8e85-ebcb2af01386.png)

**Comment by ekzhu** [comment]
@sameertikoo cool. Just note that you can also try [SetSimilaritySearch](https://github.com/ekzhu/SetSimilaritySearch) to get the pairs. This way you can get the exact pairs (no false positives or negatives) -- if that's something you care about.
